study:
  study_name: !!str dartmouth
  dataset_type: !!str GramStains
  svs_dir: !!str /pool2/data/WSI_GramStains/Dartmouth
  json_path: !!str /pool2/users/jackm/Dartmouth/Dartmouth_gram_stains.json
  stratify_by: !!str morphology
  num_folds: !!int 5
  image_extension: !!str .svs

patch:
  magnification: !!float 40
  original_magnification: !!float 40
  svs_meta: !!str meta/dartmouth_svs.pickle
  patch_size: !!int 112
  filtering_style: !!str default
  mag_mask: !!float 2.5
