#""" Stage 1: Tissue Extraction
#"""
src_1:
- !!str ./slides
# Source folder(s) containing slides (and annotations)

dst_1:
- !!str ./tissues
# Destination(s) to store extracted tissues

target_magnification: !!float 10
# Target magnification (typical values: 10, 20, 40)
# For example, using 10 is 2x downsampling from 20X and 4x downsampling from 40X.
# For debugging, set a smaller value for faster trial and error.

use_progress_bar: !!bool False
# Set True if you want a fancy progress bar.

#tissueloc_config:
   #max_img_size: !!int # default: 4096
   #smooth_sigma: !!int 13 # default: 13
   #thresh_val: !!float 0.80 # default: 0.80 (Recommended: 0.85)
   #min_tissue_size: !!int #default 10000
# To override default tissueloc sparameters, uncomment `tissueloc_config` and
# corresponding parameters above.
# Among those parameters, `thresh_val` is the most important parameter. If you choose smalle value
# (e.g., 0.75), it tends to split a slide into small tissues. If you choose large value,
# such as 1.0, it treats a whole slide as single tissue without any tissue detection,
# which may be useful for making a thumbnail of each slide. Recommended value is 0.85,
# but it depends on datasets and tasks.

#""" Shared: Stage 1 & 2
#"""
num_workers: !!int 4
# The number of threads. To enable multiprocess, set True for `multiprocess`.

slide_extension: !!str svs
# Choose either 'tif' or 'svs'.

opt1:
    - !!str ''
# Wildcard options for future extension.
# For example, current scripts use this field to specify a path when annotations
# are stored in different folder.

action_no_xml: !!str raise
# Choose an action for slides without annotation.
# options are:
#   raise: (default) raise an error. most conservative but best when slides must
#         have corresponding annotation files.
#   skip: skip slides. Use this option if you do not need non-annotated slides. 
#         Make sure to run script0 first to know which slides are going to be skipped. 
#   process: process slides anyway. Useful when you apply unsupervised methods.
#         Also pay attention to `extract_notannotated` parameter.

use_userdefined_has_xml: !!bool False
# Set True if you process DH annoation
# (Use 0_match_files.py to validate the xml and svs match.)

multiprocess: !!bool False
# Set True to enable multiprocessing (be careful, MT doesn't show error messages if any)

image_suffix: !!str png
# File extension of tissues and patches


#""" Stage 2: Patch Extraction
#"""
src_2:
    - !!str ./tissues
# Typically this should be the same as dst_1

dst_2:
    - !!str ./patches

window_size: !!int 224
# Patch size (both height and width)

overlap_factor: !!float 0.333
# Extract overlapping patches.
# For example, 0 for no overlap, 0.333 for 1/3 overlap

tissue_threshold: !!float 0.7
# A patch with at least this ratio threshold is extracted.
# For example, 0.7 means at least 70% area of a patch should have be tissues.
# The tissue/background detection is done with tissueloc in the first stage.


extract_notannotated: !!bool False
# Extract patches without annotation
# Useful for extracting negative/normal patches.


#""" YAML SYNTAX:
#      - is for a list
#      !! is for explicit data type
#
#    Loading:
#    >>> import yaml
#    >>>  f = open('config.yaml')
#    >>> config = yaml.safe_load(f)
#
#"""