# Use case: generate thumbnails of slides.


#""" Stage 1: Tissue Extraction
#"""
src_1:
- !!str ./testdata/0_test1
# Source folder(s) containing slides (and annotations)

dst_1:
- !!str ./testdata/1_tissues_t1_thumbnail
# Destination(s) to store extracted tissues

target_magnification: !!float 0.5
# Target magnification (typical values: 10, 20, 40)
# For debugging, set a smaller value for faster trial and error.

use_progress_bar: !!bool False
# Set True if you want a fancy progress bar.

tissueloc_config:
   #max_img_size: !!int # default: 4096
   #smooth_sigma: !!int 13 # default: 13
   thresh_val: !!float 1.00 # default: 0.80 (e.g., 1.0 for no tissue detection. 0.85 seems to work better.)
   #min_tissue_size: !!int #default 10000
# To override default tissueloc sparameters, uncomment `tissueloc_config` and
# corresponding parameters.


#""" Shared: Stage 1 & 2
#"""
num_workers: !!int 4
# The number of threads. To enable multiprocess, set True for `multiprocess`.

slide_extension: !!str tif
# Choose either 'tif' or 'svs'.

opt1:
    - !!str ''
# Wildcard options for future extension.
# For example, current scripts use this field to specify a path when annotations
# are stored in different folder.

action_no_xml: !!str raise
# Choose an action for slides without annotation.
# options are:
#   raise: (default) raise an error. most conservative but best when slides must
#         have corresponding annotation files.
#   skip: skip slides. Use this option if you do not need non-annotated slides. 
#         Make sure to run script0 first to know which slides are going to be skipped. 
#   process: process slides anyway. Useful when you apply unsupervised methods.
#         Also pay attention to `extract_notannotated` parameter.

use_userdefined_has_xml: !!bool False
# Set True if you process DH annoation
# (Use 0_match_files.py to validate the xml and svs match.)

multiprocess: !!bool False
# Set True to enable multiprocessing (be careful, MT doesn't show error messages if any)

image_suffix: !!str png
# File extension of tissues and patches
