# Test case 2: slides and xmls are in different folders
# Images and annotation files used in this test can be downloaded from
# [CAMELYON sample](https://www.dropbox.com/s/fegzxxsfycy1shf/testdata.zip?dl=0) (2.7GB).


#""" Stage 1 Parameters: Tissue Extraction
# Corresponding scrits:
# - 0_match_files.py
# - 1_extract_tissues.py
#"""
src_1:
- !!str ./testdata/0_test2_slide

dst_1:
- !!str ./testdata/1_tissues_t2

csv_as_data_source: !!bool False
target_magnification: !!float 10
use_progress_bar: !!bool False

tissueloc_config:
   max_img_size: !!int 4096 # default: 4096
   smooth_sigma: !!int 13 # default: 13
   thresh_val: !!float 0.80 # default: 0.80 (Recommended: 0.85)
   min_tissue_size: !!int 10000 #default 10000

slide_extension: !!str tif
opt1:
    - !!str ./testdata/0_test2_xml

action_no_xml: !!str raise
use_userdefined_has_xml: !!bool False

#""" Shared Parameters: Stage 1 & 2
# Corresponding scrits:
# - 0_match_files.py
# - 1_extract_tissues.py
# - 2_extract_patches.py
#"""
num_workers: !!int 4
multiprocess: !!bool False
image_suffix: !!str png
flattening: !!bool False


#""" Stage 2 Parameters: Patch Extraction
# Corresponding scrits:
# - 2_extract_patches.py
src_2:
    - !!str ./testdata/1_tissues_t2

dst_2:
    - !!str ./testdata/2_patches_t2

window_size: !!int 256
overlap_factor: !!float 0.333
tissue_threshold: !!float 0.7
extract_notannotated: !!bool True
ignore_class: !!bool False
